name: Deploy to staging

on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - name: Test SSH setup
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOST: ${{ secrets.KNOWN_HOST }}

        run: |
          set -e

          mkdir -p ~/.ssh

          printf '%s\n' "$SSH_PRIVATE_KEY" > ~/.ssh/ssh_key
          chmod 600 ~/.ssh/ssh_key

          printf '%s\n' "$KNOWN_HOST" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          echo "===== known_hosts ====="
          cat ~/.ssh/known_hosts

          echo "===== SSH keyscan/check ====="
          ssh-keygen -lf ~/.ssh/known_hosts

          echo "===== SSH config test ====="
          ssh -vvv \
            -i ~/.ssh/ssh_key \
            -o UserKnownHostsFile="$HOME/.ssh/known_hosts" \
            -o StrictHostKeyChecking=yes \
            ubuntu@3.235.138.41 \
            "echo SSH_CONNECTION_SUCCESS"