name: Deploy to staging
on:
    push:
        branches: [ main ]
jobs:
    redeploy_everything:
        runs-on: ubuntu-latest
        name: Deploying everything to the staging cluster

        steps:
            - run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}"" &> ~/ssh_key
                ssh -i ~/ssh_key root@3.235.138.41
                cd bms/ && git pull
                pnpm run install
                pnpm run build
                pm2 restart fe-server
                pm2 restart http-server
                pm2 restart ws-server
